name:  appengine_channel
description: A Dart wrapper for the Google App Engine Channel API.
version: 0.1.1
author: Justin Fagnani <justinfagnani@google.com>
homepage: http://code.google.com/p/gae-channel-api-dart/
dependencies:
  browser: any
  js: any
  unittest: any
