name:  appengine_channel
description: App Engine Channel API for Dart
version: 0.2.0
author: Justin Fagnani <justinfagnani@google.com>
homepage: https://github.com/dart-lang/gae-channel-api
dependencies:
  browser: '>=0.9.0<2.0.0'
  unittest: '>=0.9.0<2.0.0'
